=== Drake103/projectFieldWarning/src/FieldWarning/Assets/Units/Resources/UnitConfigSchema.json
{
    "$schema": "http://json-schema.org/schema#",

    "definitions": {
        "Data": {
            "type": "object",
            "description": "Values for the unit's Data component\n\nSee: <PFW.Units.Component.Data.DataComponent>",
            "additionalProperties": false,
            "required": [
                "MovementSpeed",
                "ReverseSpeed",
                "AccelRate",
                "MaxRotationSpeed",
                "MinTurnRadius",
                "MaxLateralAccel",
                "Suspension",
                "MaxHealth",
                "Length",
                "Width"
            ],
            "properties": {
                "MovementSpeed": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "ReverseSpeed": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "AccelRate": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "MaxRotationSpeed": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "MinTurnRadius": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "MaxLateralAccel": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "Suspension": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "MaxHealth": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "Length": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "Width": {
                    "type": "number",
                    "description": "TODO: Add description"
                }
            }
        },

        "Mobility": {
            "type": "object",
            "description": "Values for the unit's mobility type\n\nSee: <MobilityType>",
            "additionalProperties": false,
            "required": [
                "SlopeSensitivity",
                "DirectionalSlopeSensitivity",
                "PlainSpeed",
                "ForestSpeed",
                "WaterSpeed"
            ],
            "properties": {
                "SlopeSensitivity": {
                    "type": "number",
                    "description": "More all-terrain units like infantry should have reduced slope sensitivity"
                },
                "DirectionalSlopeSensitivity": {
                    "type": "number",
                    "description": "A value of 0.5 means the unit will go the same speed on flat terrain as it does on a 30 degree downhill incline"
                },
                "PlainSpeed": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "ForestSpeed": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "WaterSpeed": {
                    "type": "number",
                    "description": "TODO: Add description"
                }
            }
        },
        
        "Weapons": {
            "type": "object",
            "description": "TODO",
            "properties": {
                "Children": {
                    "type": "array",
                    "description": "TODO",
                    "items": {
                        "type": "object",
                        "description": "TODO",
                        "required": [ 
                            "Priority",
                            "Handle"
                        ],
                        "properties": {
                            "Priority": {
                                "type": "number",
                                "description": "When multiple turrets are trying to rotate a shared parent to aim at their chosen targets, the turret with a higher priority number wins. For example, a tank turret with a cannon and coax machinegun will always turn toward infantry if the machinegun has higher priority, and toward enemy armor if the cannon has higher priority."
                            },
                            "WeaponType": {
                                "type": "string",
                                "description": "TODO: Add description",
                                "enum": [ "cannon", "howitzer" ]
                            },
                            "TurretRef": {
                                "type": "string",
                                "description": "TODO: Add description"
                            },
                            "MountRef": {
                                "type": "string",
                                "description": "TODO: Add description"
                            },
                            "ArcHorizontal": {
                                "type": "number",
                                "description": "TODO: Add description"
                            },
                            "ArcUp": {
                                "type": "number",
                                "description": "TODO: Add description"
                            },
                            "ArcDown": {
                                "type": "number",
                                "description": "TODO: Add description"
                            },
                            "RotationRate": {
                                "type": "number",
                                "description": "TODO: Add description"
                            }
                        }
                    }
                },
                "TurretRef": {
                    "type": "string",
                    "description": "Used to find the child of the art object representing the turret."
                },
                "MountRef": {
                    "type": "string",
                    "description": "TODO: Add description"
                },
                "ArcHorizontal": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "ArcUp": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "ArcDown": {
                    "type": "number",
                    "description": "TODO: Add description"
                },
                "RotationRate": {
                    "type": "number",
                    "description": "TODO: Add description"
                }
            }
        }
    },

    "title": "Unit Config Schema",
    "type": "object",
    "required": [
        "$schema",
        "ID",
        "CategoryKey",
        "Name",
        "Price",
        "PrefabPath",
        "Data",
        "Mobility"
    ],
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "ID": {
            "type": "string",
            "description": "A unique ID for this unit.\n\nShould follow the format: `Unit__[category]--[model]`\ne.g.: `Unit__TNK--M1A2`",
            "pattern": "^Unit__(HEL|INF|LOG|REC|SUP|TNK|VHC)--[-a-zA-Z0-9]+$"
        },
        "CategoryKey": {
            "type": "string",
            "description": "The category of this unit.\n\nSee: <PFW.Model.Armory.UnitCategory>",
            "enum": [ "LOG", "SUP", "INF", "TNK", "REC", "VHC", "HEL" ]
        },
        "Name": {
            "type": "string",
            "description": "The full, human-friendly name of this unit.\n\nFor use in unit labels, the deck builder, etc."
        },
        "Price": {
            "type": "number",
            "description": "(float) The cost of purchasing this unit."
        },
        "PrefabPath": {
            "description": "Path to the unit's prefab, relative to any Resources directory.\n\nNOTE: The prefab should mainly have networked components that need to be synched between clients and the server, and will be augmented with 'art' after being spawned.",
            "type": "string"
        },
        "ArtPrefabPath": {
            "description": "Path to the unit's art prefab, relative to any Resources directory.\n\nArt is the non-networked part of a unit, added clientside after the unit has been spawned.",
            "type": "string"
        },
        "Data": {
            "$ref": "#/definitions/Data"
        },
        "Mobility": {
            "$ref": "#/definitions/Mobility"
        },
        "Weapons": {
            "$ref": "#/definitions/Weapons"
        }
    }
}

=== Drake103/projectFieldWarning/src/FieldWarning/Assets/Units/Resources/TNK/M1A2.json
{
    "$schema": "../UnitConfigSchema.json",

    "ID": "Unit__TNK--M1A2",
    "CategoryKey": "TNK",
    "Name": "M1A2 Abrams",
    "Price": 20,
    "PrefabPath": "TNK/M1Ax",

    "Data": {
        "MovementSpeed": 50,
        "ReverseSpeed": 15,
        "AccelRate": 13,
        "MaxRotationSpeed": 50,
        "MinTurnRadius": 0,
        "MaxLateralAccel": 15,
        "Suspension": 0.01,
        "MaxHealth": 10,
        "Length": 12,
        "Width": 7
    },

    "Mobility": {
        "SlopeSensitivity": 2,
        "DirectionalSlopeSensitivity": 0.6,
        "PlainSpeed": 0.4,
        "ForestSpeed": 0.2,
        "WaterSpeed": 0
    }
}

=== Drake103/projectFieldWarning/src/FieldWarning/Assets/Units/Resources/TNK/M1A1.json
{
    "$schema": "../UnitConfigSchema.json",

    "ID": "Unit__TNK--M1A1",
    "CategoryKey": "TNK",
    "Name": "M1A1 Abrams",
    "Price": 15,
    "PrefabPath": "TNK/M1Ax",

    "Data": {
        "MovementSpeed": 40,
        "ReverseSpeed": 12.5,
        "AccelRate": 11.5,
        "MaxRotationSpeed": 40,
        "MinTurnRadius": 0,
        "MaxLateralAccel": 15,
        "Suspension": 0.01,
        "MaxHealth": 7.5,
        "Length": 12,
        "Width": 7
    },

    "Mobility": {
        "SlopeSensitivity": 2,
        "DirectionalSlopeSensitivity": 0.6,
        "PlainSpeed": 0.4,
        "ForestSpeed": 0.2,
        "WaterSpeed": 0
    }
}

=== Drake103/projectFieldWarning/src/FieldWarning/Assets/Units/Resources/TNK/TestTank.json
{
    "$schema": "../UnitConfigSchema.json",

    "ID": "Unit__TNK--TestTank",
    "CategoryKey": "TNK",
    "Name": "TestTank",
    "Price": 20,
    "PrefabPath": "2Turret",
    "ArtPrefabPath": "SampleTankArt",

    "Data": {
        "MovementSpeed": 500,
        "ReverseSpeed": 15,
        "AccelRate": 13,
        "MaxRotationSpeed": 50,
        "MinTurnRadius": 0,
        "MaxLateralAccel": 15,
        "Suspension": 0.01,
        "MaxHealth": 10,
        "Length": 12,
        "Width": 7
    },

    "Mobility": {
        "SlopeSensitivity": 2,
        "DirectionalSlopeSensitivity": 0.6,
        "PlainSpeed": 0.4,
        "ForestSpeed": 0.2,
        "WaterSpeed": 0
    },
    
    "Weapons": {
        "Turret": {
            "Children": [
                {
                    "Priority": 1,
                    "WeaponType": "cannon",
                    "TurretRef": "Main_Barrel",
                    "MountRef": "Main_Turret",
                    "ArcHorizontal": 3,
                    "ArcUp": 40,
                    "ArcDown": 20,
                    "RotationRate": 40
                },
                {
                    "Priority": 2,
                    "WeaponType": "cannon",
                    "TurretRef": "Minigun",
                    "MountRef": "Main_Turret",
                    "ArcHorizontal": 90,
                    "ArcUp": 40,
                    "ArcDown": 20,
                    "RotationRate": 40
                }
            ],
            "TurretRef": "Main_Turret",
            "MountRef": "Main_Body",
            "ArcHorizontal": 180,
            "ArcUp": 0,
            "ArcDown": 0,
            "RotationRate": 40
        }
    }
}

=== Drake103/projectFieldWarning/src/FieldWarning/Assets/Units/Resources/TNK/FastTank.json
{
    "$schema": "../UnitConfigSchema.json",

    "ID": "Unit__TNK--FastTank",
    "CategoryKey": "TNK",
    "Name": "FastTank",
    "Price": 20,
    "PrefabPath": "TNK/M1Ax",

    "Data": {
        "MovementSpeed": 500,
        "ReverseSpeed": 15,
        "AccelRate": 13,
        "MaxRotationSpeed": 50,
        "MinTurnRadius": 0,
        "MaxLateralAccel": 15,
        "Suspension": 0.01,
        "MaxHealth": 10,
        "Length": 12,
        "Width": 7
    },

    "Mobility": {
        "SlopeSensitivity": 2,
        "DirectionalSlopeSensitivity": 0.6,
        "PlainSpeed": 0.4,
        "ForestSpeed": 0.2,
        "WaterSpeed": 0
    }
}
